# in fact all the below should be configured as env vars
notion:
  url: https://api.notion.com/v1/databases/45b4172264ee4320b09336b285ab7521/query
  token: ${NOTION_TOKEN}
channel:
  urls:
    DISCORD: ${DISCORD_CHANNEL_URL}
    OTHER: https://future.use.io/fake/channel-id
#    NEW: https://not-yet-supported/connector

# H2 properties
spring:
  datasource:
    url=jdbc:h2:mem:jpa_jbd
    driverClassName=org.h2.Driver
    username=sa
    password=

  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true